version: "2"

services:
  primary:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    build: ./pg
    container_name: pglogical
    networks:
      - dockernet
    ports:
      - "5432:5432"
networks:
  dockernet:
    driver: bridge
